# Site Info
title:              "Frank Martin | Software Engineer"
description:        "Expert web developer and Technical Director at Digital Results in Hertfordshire, UK"
google_verify:      Lis9oaHLvVH5CHITSf4Hk6Gp5ZZo519VRsCqZqTvjhs # Put your Google Verification here
google_analytics:   UA-44826507-4 # Put your Google Analytics code

# Author Info
author_name:        "Frank Martin"
author_email:       frank.martin.86@hotmail.com
author_gravatar:    ee2c247f343e1b7f7f4b651dcea162b8 # Gravatar md5 hash
twitter_username:   frank_martin_86

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /:year/:month/:day/:title # Post permalink
timezone:           Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:        rouge
#markdown:           redcarpet
#redcarpet:
#    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
